---
# maintains ports, bianry or repo urls

org: encapsulate

default_node_types:
  - validator
  - default

tmp_dir: /tmp

go:
  root: /usr/local/go
  path: "{{ tmp_dir }}/go"
  module111: "on"

celestia:
  port_prefix: 104
  validator:
    source_url:
    ports:
      suffix:
        p2p: 56
        rpc: 57
        abci: 58
        prometheus: 60
        pprof: 61
        rest_api: 17
        rosetta: 80
        grpc: 90
        grpc_web: 91
  fullnode:
    source_url:
    ports:
      suffix:
        p2p: 56
        rpc: 57
        abci: 58
        prometheus: 60
        pprof: 61
        rest_api: 17
        rosetta: 80
        grpc: 90
        grpc_web: 91
  bridge:
    source_url: https://github.com/celestiaorg/celestia-node
    ports:
      suffix:
        rpc: 85
        p2p: 86
        gateway: 87
