---
# maintains versions and can overwrite all.yml
celestia:
  bridge:
    version: v0.21.3-mocha
    go:
      version: 1.23.0
    chain_id: mocha
    metrics_endpoint: "{{ monitor_server_dns }}:4319"

  bridge_grpc:
    ip: grpc-1.testnet.celestia.nodes.guru
    grpc_port: 10790
