---
- name: Include the ufw rules var file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules for each node type
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ bridge_ufw_rules }}"

- name: Include setup zfs task
  ansible.builtin.include_tasks: setup_zfs.yml
  when: zfs_setup | default(false) | bool

- name: Include user creation task for celestia
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ bridge_home_dir }}"
    directories: "{{ bridge_directories }}"
    log_file_path: "{{ bridge_log_file_path }}"

- name: Include build binary task
  ansible.builtin.include_tasks: build_binary.yml

- name: Copy bridge configuration file
  ansible.builtin.template:
    src: "{{ env }}/config.toml.j2"
    dest: "{{ bridge_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: fetch_validator_keys | default(false) | bool
  block:
    - name: Fetch node NJ3 key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ bridge_node_key_nj3_file_name }}"
        secret_destination_path: "{{ bridge_node_key_nj3_path }}"
        secret_type: json

    - name: Fetch Node OAZ key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ bridge_node_key_oaz_file_name }}"
        secret_destination_path: "{{ bridge_node_key_oaz_path }}"
        secret_type: json

- name: Copy celestia bridge node systemd service file
  ansible.builtin.template:
    src: "{{ env }}/bridge.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
