---
- name: Include the default vars file
  ansible.builtin.include_vars:
    file: roles/bridge/defaults/main.yml

- name: Include the vars file
  ansible.builtin.include_vars:
    file: roles/bridge/vars/main.yml

- name: Copy bridge configuration file
  ansible.builtin.template:
    src: "roles/bridge/templates/{{ env }}/config.toml.j2"
    dest: "{{ bridge_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service
